packaging_format = 2

id = "mautic"
name = "Mautic"
description.en = "Marketing Automation Software"
description.fr = "Logiciel d'automatisation marketing"

version = "4.4.7~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0-only"
website = "https://www.mautic.org/"
demo = "https://www.mautic.org/demo"
admindoc = "https://docs.mautic.org/en"
code = "https://github.com/mautic/mautic"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Mautic will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Mautic sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/mautic/mautic/releases/download/4.4.8/4.4.8.zip"
        sha256 = "e238648fb0c31e500383ac7b93e04b3a2dfcfd2335b756db36907c2ffd0a60ac"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    
    [resources.apt]
    packages = "mariadb-server php8.0-imap php8.0-gmp php8.0-curl php8.0-intl php8.0-mbstring php8.0-xmlrpc php8.0-mysql php8.0-bcmath php8.0-gd php8.0-xml php8.0-cli php8.0-zip"

    [resources.database]
    type = "mysql"
