#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mautic"
name = "Mautic"
description.en = "Marketing Automation Software"
description.fr = "Logiciel d'automatisation marketing"

version = "5.2.3~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://www.mautic.org/"
demo = "https://www.mautic.org/demo"
admindoc = "https://docs.mautic.org/en"
code = "https://github.com/mautic/mautic"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Mautic will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Mautic sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/mautic/mautic/releases/download/5.2.3/5.2.3.zip"
    sha256 = "c6acb77e9c362ce40a4269bc904ae92127119525f9c6b1fa1fab6d3c39681298"
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "\\d+(\\.\\d+)+\\.zip"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-imap, php8.3-gmp, php8.3-curl, php8.3-intl, php8.3-mbstring, php8.3-xmlrpc, php8.3-mysql, php8.3-bcmath, php8.3-gd, php8.3-xml, php8.3-cli, php8.3-zip"

    [resources.database]
    type = "mysql"
