packaging_format = 2

id = "mautic"
name = "Mautic"
description.en = "Marketing Automation Software"
description.fr = "Logiciel d'automatisation marketing"

version = "5.1.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://www.mautic.org/"
demo = "https://www.mautic.org/demo"
admindoc = "https://docs.mautic.org/en"
code = "https://github.com/mautic/mautic"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Mautic will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Mautic sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/mautic/mautic/releases/download/5.1.0/5.1.0.zip"
        sha256 = "354786dcd68bd080452b47b6992411690079a12235ba9bda93b824b63f4f3a28"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-imap, php8.4-gmp, php8.4-curl, php8.4-intl, php8.4-mbstring, php8.4-xmlrpc, php8.4-mysql, php8.4-bcmath, php8.4-gd, php8.4-xml, php8.4-cli, php8.4-zip"

    [resources.database]
    type = "mysql"
