#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=2

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

chmod -R g+w "$install_dir/app/config/"
chmod -R g+w "$install_dir/media/files/"
chmod -R g+w "$install_dir/media/images/"
chmod -R g+w "$install_dir/translations/"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_add_config --template="cron" --destination="/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# INSTALLING THE APP
#=================================================
ynh_script_progression --message="Installing $app..." --weight=1

pushd "$install_dir"
	ynh_exec_as $app php${phpversion} bin/console mautic:install $domain \
	--db_driver="pdo_mysql" --db_host="localhost" --db_port="3306" --db_name="$db_name" --db_user="$db_user" --db_password="$db_pwd" --db_backup_tables="false" \
	--admin_email="$email" --admin_password="$password" --admin_username="$admin"
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
