#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep="config/local.php media/files media/images translations" #--full_replace=1

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

chmod -R g+w "$install_dir/app/config/"
chmod -R g+w "$install_dir/media/files/"
chmod -R g+w "$install_dir/media/images/"
chmod -R g+w "$install_dir/translations/"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# INSTALLING THE APP
#=================================================
ynh_script_progression --message="Installing $app..." --weight=1

pushd "$install_dir"
	ynh_exec_as $app php${phpversion} bin/console cache:clear
	ynh_exec_as $app php${phpversion} bin/console mautic:update:apply --finish
	ynh_exec_as $app php${phpversion} bin/console doctrine:migration:migrate --no-interaction
	ynh_exec_as $app php${phpversion} bin/console doctrine:schema:update --no-interaction --force
	ynh_exec_as $app php${phpversion} bin/console cache:clear
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
