#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M

ynh_app_setting_set_default --key=php_memory_limit --value=512M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config/local.php media/files media/images translations"

chmod -R g+w "$install_dir/app/config/"
chmod -R g+w "$install_dir/media/files/"
chmod -R g+w "$install_dir/media/images/"
chmod -R g+w "$install_dir/translations/"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# FINISHING INSTALL
#=================================================
ynh_script_progression --message="Cleaning $app cach..." --weight=1

pushd "$install_dir"
	ynh_exec_as $app php${phpversion} bin/console mautic:update:apply --finish
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
